export const homeConstant = { 

    FETCH_COUNTRY_LIST_FULFILLED : 'FETCH_COUNTRY_LIST_FULFILLED',
    FETCH_COUNTRY_LIST_REJECTED : 'FETCH_COUNTRY_LIST_REJECTED',

    FETCH_BANK_LIST_FULFILLED : 'FETCH_BANK_LIST_FULFILLED',
    FETCH_BANK_LIST_REJECTED : 'FETCH_BANK_LIST_REJECTED',

    FETCH_RECHARGE_PACKS_FULFILLED : 'FETCH_RECHARGE_PACKS_FULFILLED',
    FETCH_RECHARGE_PACKS_REJECTED : 'FETCH_RECHARGE_PACKS_REJECTED',

    FETCH_REMIT_PACKS_FULFILLED : 'FETCH_REMIT_PACKS_FULFILLED',
    FETCH_REMIT_PACKS_REJECTED : 'FETCH_REMIT_PACKS_REJECTED',

    FETCH_REMIT_SETTING_FULFILLED : 'FETCH_REMIT_SETTING_FULFILLED',
    FETCH_REMIT_SETTING_REJECTED : 'FETCH_REMIT_SETTING_REJECTED',

    FETCH_CREATE_PAYMENT_INTENT_FULFILLED: 'FETCH_CREATE_PAYMENT_INTENT_FULFILLED',
    FETCH_CREATE_PAYMENT_INTENT_REJECTED : 'FETCH_CREATE_PAYMENT_INTENT_REJECTED',

    FETCH_SMS_CREDITS_DETAIL_FULFILLED : 'FETCH_SMS_CREDITS_DETAIL_FULFILLED',
    FETCH_SMS_CREDITS_DETAIL_REJECTED : 'FETCH_SMS_CREDITS_DETAIL_REJECTED',

    FETCH_SEND_SMS_FULFILLED : "FETCH_SEND_SMS_FULFILLED",
    FETCH_SEND_SMS_REJECTED : 'FETCH_SEND_SMS_REJECTED',

    FETCH_SMS_PACKAGES_FULFILLED : 'FETCH_SMS_PACKAGES_FULFILLED',
    FETCH_SMS_PACKAGES_REJECTED : 'FETCH_SMS_PACKAGES_REJECTED',

    FETCH_SMS_PACKAGES_DETAIL_FULFILLED : 'FETCH_SMS_PACKAGES_DETAIL_FULFILLED',
    FETCH_SMS_PACKAGES_DETAIL_REJECTED : 'FETCH_SMS_PACKAGES_DETAIL_REJECTED',

    FETCH_APPLY_COUPON_FULFILLED : 'FETCH_APPLY_COUPON_FULFILLED',
    FETCH_APPLY_COUPON_REJECTED : 'FETCH_APPLY_COUPON_REJECTED',

    FETCH_SUBMIT_REQUEST_FULFILLED : 'FETCH_SUBMIT_REQUEST_FULFILLED',
    FETCH_SUBMIT_REQUEST_REJECTED : 'FETCH_SUBMIT_REQUEST_REJECTED',

    FETCH_PROCESS_REMIT_FULFILLED : 'FETCH_PROCESS_REMIT_FULFILLED',
    FETCH_PROCESS_REMIT_REJECTED : 'FETCH_PROCESS_REMIT_REJECTED',

    FETCH_REMIT_EXTRA_CHARGE_FULFILLED : 'FETCH_REMIT_EXTRA_CHARGE_FULFILLED',
    FETCH_REMIT_EXTRA_CHARGE_REJECTED : 'FETCH_REMIT_EXTRA_CHARGE_REJECTED',

    FETCH_HISTORY_DATA_FULFILLED : 'FETCH_HISTORY_DATA_FULFILLED',
    FETCH_HISTORY_DATA_REJECTED : 'FETCH_HISTORY_DATA_REJECTED',

    FETCH_SEARCH_HISTORY_DATA_FULFILLED : 'FETCH_SEARCH_HISTORY_DATA_FULFILLED',
    FETCH_SEARCH_HISTORY_DATA_REJECTED : 'FETCH_SEARCH_HISTORY_DATA_REJECTED',

    FETCH_USER_DATA_FULFILLED : 'FETCH_USER_DATA_FULFILLED',
    FETCH_USER_DATA_REJECTED : 'FETCH_USER_DATA_REJECTED',

    FETCH_SMS_HISTORY_DATA_FULFILLED : 'FETCH_SMS_HISTORY_DATA_FULFILLED',
    FETCH_SMS_HISTORY_DATA_REJECTED : 'FETCH_SMS_HISTORY_DATA_REJECTED',

    FETCH_REQUEST_HISTORY_DATA_FULFILLED : 'FETCH_REQUEST_HISTORY_DATA_FULFILLED',
    FETCH_REQUEST_HISTORY_DATA_REJECTED : 'FETCH_REQUEST_HISTORY_DATA_REJECTED',

    FETCH_SEARCH_REQUEST_DATA_FULFILLED : 'FETCH_SEARCH_REQUEST_DATA_FULFILLED',
    FETCH_SEARCH_REQUEST_DATA_REJECTED : 'FETCH_SEARCH_REQUEST_DATA_REJECTED',

    FETCH_SEARCH_SMS_DATA_FULFILLED : 'FETCH_SEARCH_SMS_DATA_FULFILLED',
    FETCH_SEARCH_SMS_DATA_REJECTED : 'FETCH_SEARCH_SMS_DATA_REJECTED',

    FETCH_PURCHASE_HISTORY_DATA_FULFILLED : 'FETCH_PURCHASE_HISTORY_DATA_FULFILLED',
    FETCH_PURCHASE_HISTORY_DATA_REJECTED : 'FETCH_PURCHASE_HISTORY_DATA_REJECTED',

    FETCH_SEARCH_PURCHASE_DATA_FULFILLED : 'FETCH_SEARCH_PURCHASE_DATA_FULFILLED',
    FETCH_SEARCH_PURCHASE_DATA_REJECTED : 'FETCH_SEARCH_PURCHASE_DATA_REJECTED',

    FETCH_REQUEST_DASHBOARD_FULFILLED : 'FETCH_REQUEST_DASHBOARD_FULFILLED',
    FETCH_REQUEST_DASHBOARD_REJECTED : 'FETCH_REQUEST_DASHBOARD_REJECTED',

    FETCH_REMIT_DASHBOARD_FULFILLED : 'FETCH_REMIT_DASHBOARD_FULFILLED',
    FETCH_REMIT_DASHBOARD_REJECTED : 'FETCH_REMIT_DASHBOARD_REJECTED',

    FETCH_FAQ_DATA_FULFILLED : 'FETCH_FAQ_DATA_FULFILLED',
    FETCH_FAQ_DATA_REJECTED : 'FETCH_FAQ_DATA_REJECTED',

    FETCH_SEARCH_REQUEST_DASHBOARD_FULFILLED : 'FETCH_SEARCH_REQUEST_DASHBOARD_FULFILLED',
    FETCH_SEARCH_REQUEST_DASHBOARD_REJECTED : 'FETCH_SEARCH_REQUEST_DASHBOARD_REJECTED',

    FETCH_SEARCH_SENT_REMIT_FULFILLED : 'FETCH_SEARCH_SENT_REMIT_FULFILLED',
    FETCH_SEARCH_SENT_REMIT_REJECTED : 'FETCH_SEARCH_SENT_REMIT_REJECTED',

    FETCH_SEARCH_RECIEVE_REMIT_FULFILLED : 'FETCH_SEARCH_RECIEVE_REMIT_FULFILLED',
    FETCH_SEARCH_RECIEVE_REMIT_REJECTED : 'FETCH_SEARCH_RECIEVE_REMIT_REJECTED',

    FETCH_STRIPE_PAYMENT_API_FULFILLED : 'FETCH_STRIPE_PAYMENT_API_FULFILLED',
    FETCH_STRIPE_PAYMENT_API_REJECTED : 'FETCH_STRIPE_PAYMENT_API_REJECTED',

    FETCH_STRIPE_SMS_PAYMENT_API_FULFILLED : 'FETCH_STRIPE_SMS_PAYMENT_API_FULFILLED',
    FETCH_STRIPE_SMS_PAYMENT_API_REJECTED : 'FETCH_STRIPE_SMS_PAYMENT_API_REJECTED',

    FETCH_PAYPAL_PAYMENT_API_FULFILLED : 'FETCH_PAYPAL_PAYMENT_API_FULFILLED',
    FETCH_PAYPAL_PAYMENT_API_REJECTED : 'FETCH_PAYPAL_PAYMENT_API_REJECTED',

    FETCH_PAYPAL_SMS_PAYMENT_API_FULFILLED : 'FETCH_PAYPAL_SMS_PAYMENT_API_FULFILLED',
    FETCH_PAYPAL_SMS_PAYMENT_API_REJECTED : 'FETCH_PAYPAL_SMS_PAYMENT_API_REJECTED',

    FETCH_GPAY_PAYMENT_API_FULFILLED : 'FETCH_GPAY_PAYMENT_API_FULFILLED',
    FETCH_GPAY_PAYMENT_API_REJECTED : 'FETCH_GPAY_PAYMENT_API_REJECTED',

    FETCH_APPLE_PAYMENT_API_FULFILLED : 'FETCH_APPLE_PAYMENT_API_FULFILLED',
    FETCH_APPLE_PAYMENT_API_REJECTED : 'FETCH_APPLE_PAYMENT_API_REJECTED',

    FETCH_GPAY_SMS_PAYMENT_API_FULFILLED : 'FETCH_GPAY_SMS_PAYMENT_API_FULFILLED',
    FETCH_GPAY_SMS_PAYMENT_API_REJECTED : 'FETCH_GPAY_SMS_PAYMENT_API_REJECTED',

    FETCH_APPLE_SMS_PAYMENT_API_FULFILLED : "FETCH_APPLE_SMS_PAYMENT_API_FULFILLED",
    FETCH_APPLE_SMS_PAYMENT_API_REJECTED : 'FETCH_APPLE_SMS_PAYMENT_API_REJECTED',

    FETCH_STRIPE_REMIT_PAYMENT_API_FULFILLED : 'FETCH_STRIPE_REMIT_PAYMENT_API_FULFILLED',
    FETCH_STRIPE_REMIT_PAYMENT_API_REJECTED : 'FETCH_STRIPE_REMIT_PAYMENT_API_REJECTED',

    FETCH_GPAY_REMIT_PAYMENT_API_FULFILLED : 'FETCH_GPAY_REMIT_PAYMENT_API_FULFILLED',
    FETCH_GPAY_REMIT_PAYMENT_API_REJECTED : 'FETCH_GPAY_REMIT_PAYMENT_API_REJECTED',

    FETCH_NOTIFICATION_LIST_DATA_FULFILLED : 'FETCH_NOTIFICATION_LIST_DATA_FULFILLED',
    FETCH_NOTIFICATION_LIST_DATA_REJECTED : 'FETCH_NOTIFICATION_LIST_DATA_REJECTED',

    FETCH_NOTIFICATION_SINGLE_READ_FULFILLED : 'FETCH_NOTIFICATION_SINGLE_READ_FULFILLED',
    FETCH_NOTIFICATION_SINGLE_READ_REJECTED : 'FETCH_NOTIFICATION_SINGLE_READ_REJECTED',

    FETCH_NOTIFICATION_ALL_READ_FULFILLED : 'FETCH_NOTIFICATION_ALL_READ_FULFILLED',
    FETCH_NOTIFICATION_ALL_READ_REJECTED : 'FETCH_NOTIFICATION_ALL_READ_REJECTED',

    FETCH_NOTIFICATION_DELETE_ALL_FULFILLED : 'FETCH_NOTIFICATION_DELETE_ALL_FULFILLED',
    FETCH_NOTIFICATION_DELETE_ALL_REJECTED : 'FETCH_NOTIFICATION_DELETE_ALL_REJECTED',
    
    DELETE_USER_DATA_FULFILLED:'DELETE_USER_DATA_FULFILLED',
    DELETE_USER_DATA_REJECTED :'DELETE_USER_DATA_REJECTED',
    
}

export const authConstant = {

    FETCH_LOGIN_BY_EMAIL_FULFILLED : 'FETCH_LOGIN_BY_EMAIL_FULFILLED',
    FETCH_LOGIN_BY_EMAIL_REJECTED : 'FETCH_LOGIN_BY_EMAIL_REJECTED',

    FETCH_SIGNUP_BY_EMAIL_FULFILLED : 'FETCH_SIGNUP_BY_EMAIL_FULFILLED',
    FETCH_SIGNUP_BY_EMAIL_REJECTED : 'FETCH_SIGNUP_BY_EMAIL_REJECTED',

    FETCH_LOGIN_BY_OTP_FULFILLED: 'FETCH_LOGIN_BY_OTP_FULFILLED',
    FETCH_LOGIN_BY_OTP_REJECTED : 'FETCH_LOGIN_BY_OTP_REJECTED',

    FETCH_SIGNUP_BY_OTP_FULFILLED : 'FETCH_SIGNUP_BY_OTP_FULFILLED',
    FETCH_SIGNUP_BY_OTP_REJECTED : 'FETCH_SIGNUP_BY_OTP_REJECTED',

    FETCH_LOGIN_BY_GOOGLE_FULFILLED : "FETCH_LOGIN_BY_GOOGLE_FULFILLED",
    FETCH_LOGIN_BY_GOOGLE_REJECTED :'FETCH_LOGIN_BY_GOOGLE_REJECTED',

    FETCH_LOGIN_BY_FACEBOOK_FULFILLED : 'FETCH_LOGIN_BY_FACEBOOK_FULFILLED',
    FETCH_LOGIN_BY_FACEBOOK_REJECTED : 'FETCH_LOGIN_BY_FACEBOOK_REJECTED',

    FETCH_UPDATE_PROFILE_FULFILLED : 'FETCH_UPDATE_PROFILE_FULFILLED',
    FETCH_UPDATE_PROFILE_REJECTED : 'FETCH_UPDATE_PROFILE_REJECTED',

    FETCH_UPDATE_PASSWORD_FULFILLED : 'FETCH_UPDATE_PASSWORD_FULFILLED',
    FETCH_UPDATE_PASSWORD_REJECTED : 'FETCH_UPDATE_PASSWORD_REJECTED',

    FETCH_SET_PIN_FULFILLED : 'FETCH_SET_PIN_FULFILLED',
    FETCH_SET_PIN_REJECTED : 'FETCH_SET_PIN_REJECTED',

    FETCH_VERIFY_PIN_FULFILLED : 'FETCH_VERIFY_PIN_FULFILLED',
    FETCH_VERIFY_PIN_REJECTED : 'FETCH_VERIFY_PIN_REJECTED',

    FETCH_FORGET_PIN_FULFILLED : 'FETCH_FORGET_PIN_FULFILLED',
    FETCH_FORGET_PIN_REJECTED : 'FETCH_FORGET_PIN_REJECTED',

    FETCH_CHECK_OTP_FULFILLED : 'FETCH_CHECK_OTP_FULFILLED',
    FETCH_CHECK_OTP_REJECTED : 'FETCH_CHECK_OTP_REJECTED',

    FETCH_RESET_PIN_FULFILLED : 'FETCH_RESET_PIN_FULFILLED',
    FETCH_RESET_PIN_REJECTED : 'FETCH_RESET_PIN_REJECTED',

    FETCH_ADD_FCM_TOKEN_FULFILLED : 'FETCH_ADD_FCM_TOKEN_FULFILLED',
    FETCH_ADD_FCM_TOKEN_REJECTED : 'FETCH_ADD_FCM_TOKEN_REJECTED',


 }